apiVersion: v1
kind: Secret
metadata:
  name: fusion-secrets
  namespace: fusion
type: Opaque
stringData:
  MONGO_URI: "mongodb://fusion-admin:fusion-secure-pass-2024@mongodb-service:27017/Ecommerce-Products?authSource=admin"
  JWT_SECRET: "fusion-jwt-super-secret-key-production-2024"
  MONGO_ROOT_PASSWORD: "fusion-secure-pass-2024"
  MONGO_ROOT_USERNAME: "fusion-admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: ecr-credentials
  namespace: fusion
type: kubernetes.io/dockerconfigjson
data:
  # This will be populated by the Jenkins pipeline ECR login step
  .dockerconfigjson: e30K
